# Jekyll Resume Theme

# Site settings
title: Roney Lacerda
email: roneylacerda@gmail.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: ""
name: Roney Lacerda
job: Designer Digital
location: Ipiranga, São Paulo - SP
languages: Data, Design e Front-end
github_username:  roneystones
twitter_username: RoneyStones
linkedin_username: roneylacerda
email_address: roneylacerda@gmail.com

# Build settings
markdown: kramdown